### ISSUE TITLE
What is going to happen with klov?

### ISSUE THREAD

**Issue by letmejustfixthat** [extent-framework/klov#27] opened 2019-04-24 08:32 UTC
We are currently considering to use klov, how ever

 The klov server...
- is not open source
- has not been updated for months
- has no roadmap at all
- is written in an age old angular version
- seems to be not thought through and is overall super beta-ish (timestamps still don't work, embedding screenshots is still super buggy, and running tests in parallel screws the whole thing up completely if not handled in the test code; just some examples)
- seems to not fit into extent software licence model (stuff in the html reports, like tags, are pro only in klov - why would one do that?)
- is poorly documented

Also...
- there are issues open for weeks without any answers

Is here anything to happen or is is dead?

**Comment by foursyth** [comment] 2019-04-24 17:20
@letmejustfixthat 

Thank you for raising these questions.  Let me try my best to answer each and would defer to @anshooarora for additional clarity.

* it being open-source is a decision taken holistically by our entire team, but it may change in the future if the user-base grows
* there have been several updates but not yet released to the public in its current state.  the front-end is also changing to 100% react which takes time to thoroughly test and make sure no functionality is lost
* because the code has not been open-sourced, the road-map is also internal to our team
* the angular front-end is moving to react
* timestamps is an open issue, haven't faced any issues embedding screenshots (examples to reproduce would help if you are having issues) and no problems with parallel execution either. Although, with parallel runs, if your test code is not written properly and clashes occur at the API level, then Klov can't do much there
* license: because additional functionality exists in the professional API, they get restricted in the community version and this difference would remain unless contributors enhance this reporter via pull requests
* documentation: always has been the Achilles heel and we're aware but given the tiny size of our team, we always prioritize the API over the server
* open issues: this is mainly because of the immense growth of the API and the amount of time spent answering queries and supporting our customers, community users in all the open repositories on GitHub, stackoverflow, emails vs the size of our team and the 14+ hour shifts we do everyday including our jobs still does not suffice to focus our energy on Klov

.. with that being said, our plans to open-source the server may materialize soon if the community grows otherwise it beats the purpose as a lot of work needs to be put into it before the codebase is community ready.

but to answer the real question: is klov dead? absolutely not. its very much the contrary.

**Comment by foursyth** [comment] 2019-04-25 01:43
Btw, are you using the .Net or Java API?

**Comment by letmejustfixthat** [comment] 2019-04-29 06:32
Thanks for you answer(s)

> because the code has not been open-sourced, the road-map is also internal to our team

That could be a subject to change, at least you should consider giving the roadmap to public. Why should we even consider investing into a pro version otherwise?

> timestamps is an open issue, haven't faced any issues embedding screenshots (examples to reproduce would help if you are having issues) and no problems with parallel execution either.

It doesn't create a lot of trust into a product if something simple as timestamps don't work, even after months of waiting (again, from my point of view considering the pro investment). I opened up a ticket but we didn't find a solution ( https://github.com/extent-framework/extentreports-java/issues/38 )
Regarding screenshots: https://github.com/extent-framework/klov-server/issues/6
Regarding parallel execution: https://github.com/extent-framework/klov-server/issues/19 

> license: because additional functionality exists in the professional API, they get restricted in the community version 

I understand that. I don't understand, how ever, why features "mixed" pro. Let's have a look a the tags for instance. I can create them in my test code, I can see them in the HTML report. How ever, I cannot see them in the klov report as they are a pro feature in the klov report. And that makes no sense to me (and seems to be a bug at first: https://github.com/extent-framework/klov-server/issues/7 ). Tags should be a "Pro Only" everywhere or not at all. That just seems somewhat not well conceived to me.

> but to answer the real question: is klov dead? absolutely not. its very much the contrary.

So, when do you think will the next update be here?

> Btw, are you using the .Net or Java API?

Currently we are using the Java API in version [4.0,4.1) and the test-ng adapter in [1.0.3,1.1.0) with klov 0.2.5

**Comment by asuarez30** [comment] 2019-04-30 15:14
@letmejustfixthat We are running into some of these same core issues. 

We are trying to execute concurrently accross multiple machines, but produce one "Build" we actually just pulled down source (using the forked dotnetcore nuget) and modified it to account for our changes. 

However, tags are still broken and so it the Attribute > States. One cannot remote a test from a state once its been added.

**Comment by letmejustfixthat** [comment] 2019-08-16 04:47
Another 4 months passed without any updates. We consider this project dead and move on.

**Comment by anshooarora** [comment] 2019-12-26 00:32
All - I had a pretty hectic year and just picked up my open-source projects 2 days ago.  I will be working on Klov soon, but want to resolve all outstanding issues with the core APIs and the adapters first.

**Comment by anshooarora** [comment] 2019-12-26 00:35
@asuarez30 It is possible to remove an entire built, but not a single test without removing it completely from the db.

**Closed as completed** 2020-07-26 18:23 UTC
